version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345qwerty
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
  django:
    container_name: news_project
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "
             python /usr/src/news/manage.py makemigrations --noinput &&
             python /usr/src/news/manage.py migrate --noinput &&
             python /usr/src/news/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/news
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
